import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import * as api from '../lib/api';

type PipelineStatus = 'idle' | 'running' | 'complete' | 'failed';
type StageStatus = 'pending' | 'running' | 'complete' | 'failed';

interface Stage {
  key: string;
  label: string;
  status: StageStatus;
  artifactId?: string;
}

interface Artifacts {
  spec?: any;
  architecture?: any;
  tasks?: any;
}

function FeedbackWidget({ artifactId }: { artifactId: string }) {
  const [submitted, setSubmitted] = useState(false);
  async function submit(rating: 'helpful' | 'needs_improvement') {
    await api.submitFeedback(artifactId, rating).catch(() => {});
    setSubmitted(true);
  }
  if (submitted) return <span className="text-[10px] text-slate-400">✓ Recorded</span>;
  return (
    <span className="inline-flex gap-1">
      <button
        onClick={() => submit('helpful')}
        className="text-slate-400 hover:text-green-600 text-xs"
        title="Helpful"
      >
        ↑
      </button>
      <button
        onClick={() => submit('needs_improvement')}
        className="text-slate-400 hover:text-orange-600 text-xs"
        title="Needs work"
      >
        ↓
      </button>
    </span>
  );
}

export default function Generate() {
  const { id: projectId } = useParams<{ id: string }>();
  const [project, setProject] = useState<any>(null);
  const [description, setDescription] = useState('');
  const [pipelineStatus, setPipelineStatus] = useState<PipelineStatus>('idle');
  const [error, setError] = useState('');
  const [stages, setStages] = useState<Stage[]>([
    { key: 'spec', label: 'Requirements', status: 'pending' },
    { key: 'architecture', label: 'Architecture', status: 'pending' },
    { key: 'tasks', label: 'Tasks', status: 'pending' },
  ]);
  const [artifacts, setArtifacts] = useState<Artifacts>({});
  const [activeTab, setActiveTab] = useState<'spec' | 'architecture' | 'tasks'>('spec');
  const [metadata, setMetadata] = useState<any>(null);

  useEffect(() => {
    if (projectId) {
      api.listProjects().then((projects) => {
        const p = projects.find((proj: any) => proj.id === projectId);
        if (p) {
          setProject(p);
          if (p.description) setDescription(p.description);
        }
      });
    }
  }, [projectId]);

  function updateStage(key: string, status: StageStatus) {
    setStages((prev) => prev.map((s) => (s.key === key ? { ...s, status } : s)));
  }

  async function runPipeline() {
    if (!projectId || description.length < 10) return;
    setPipelineStatus('running');
    setError('');
    setArtifacts({});
    setStages([
      { key: 'spec', label: 'Requirements', status: 'pending' },
      { key: 'architecture', label: 'Architecture', status: 'pending' },
      { key: 'tasks', label: 'Tasks', status: 'pending' },
    ]);

    try {
      updateStage('spec', 'running');
      const specResult = await api.generateSpec(projectId, description);
      setArtifacts((prev) => ({ ...prev, spec: specResult.artifact }));
      setMetadata(specResult.provenance);
      updateStage('spec', 'complete');

      updateStage('architecture', 'running');
      const archResult = await api.generateArchitecture(specResult.artifact.id);
      setArtifacts((prev) => ({ ...prev, architecture: archResult.artifact }));
      updateStage('architecture', 'complete');

      updateStage('tasks', 'running');
      const taskResult = await api.generateTasks(archResult.artifact.id);
      setArtifacts((prev) => ({ ...prev, tasks: taskResult.artifact }));
      updateStage('tasks', 'complete');

      setPipelineStatus('complete');
    } catch (err) {
      setError((err as Error).message);
      setPipelineStatus('failed');
      setStages((prev) =>
        prev.map((s) => (s.status === 'running' ? { ...s, status: 'failed' } : s)),
      );
    }
  }

  async function handleExport() {
    const { default: JSZip } = await import('jszip');
    const zip = new JSZip();
    const name = project?.name || 'project';

    zip.file(
      'README.md',
      `# ${name} — Engineering Package\n\nGenerated by ArchitectAI.\n\n> ${description}\n`,
    );
    if (artifacts.spec) zip.file('01_Requirements.md', formatSpec(artifacts.spec.content));
    if (artifacts.architecture)
      zip.file('02_Architecture.md', formatArch(artifacts.architecture.content));
    if (artifacts.tasks) zip.file('03_Tasks.md', formatTasks(artifacts.tasks.content));
    zip.file(
      '04_Metadata.md',
      `# Metadata\n\n- **Model:** ${metadata?.model || 'unknown'}\n- **Prompt:** ${metadata?.promptVersion || 'unknown'}\n- **Generated:** ${new Date().toISOString()}\n`,
    );

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${name.replace(/\s+/g, '_')}.zip`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function formatSpec(c: any): string {
    let md = '# Requirements\n\n';
    c.functionalRequirements?.forEach((r: any) => {
      md += `## ${r.id}: ${r.description}\n\n**Priority:** ${r.priority}\n\n`;
    });
    md += '## Acceptance Criteria\n\n';
    c.acceptanceCriteria?.forEach((a: string) => {
      md += `- ${a}\n`;
    });
    md += '\n## Constraints\n\n';
    c.constraints?.forEach((x: string) => {
      md += `- ${x}\n`;
    });
    md += '\n## Dependencies\n\n';
    c.dependencies?.forEach((x: string) => {
      md += `- ${x}\n`;
    });
    return md;
  }

  function formatArch(c: any): string {
    let md = '# Architecture\n\n';
    c.components?.forEach((x: any) => {
      md += `## ${x.name} [${x.layer}]\n\n${x.responsibilities?.map((r: string) => `- ${r}`).join('\n')}\n\n`;
    });
    md += '## Bounded Contexts\n\n';
    c.boundedContexts?.forEach((x: any) => {
      md += `### ${x.name}\n\nAggregates: ${x.aggregates?.join(', ')}\n\n`;
    });
    return md;
  }

  function formatTasks(c: any): string {
    let md = `# Tasks\n\nCoverage: ${c.traceabilityCoverage}%\n\n`;
    c.tasks?.forEach((t: any) => {
      md += `## ${t.id}: ${t.title}\n\nComplexity: ${t.complexity}/5\n\n${t.description}\n\n`;
    });
    return md;
  }

  function renderArtifact(artifact: any) {
    if (!artifact)
      return <div className="text-xs text-slate-400 py-8 text-center">Not generated yet</div>;
    const c = artifact.content;

    if (activeTab === 'spec')
      return (
        <div className="space-y-4">
          {c.functionalRequirements?.map((r: any) => (
            <div key={r.id} className="border-l-2 border-blue-200 pl-3">
              <div className="flex items-center gap-2">
                <code className="text-[10px] text-blue-600">{r.id}</code>
                <span
                  className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${r.priority === 'must' ? 'bg-red-50 text-red-700' : r.priority === 'should' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'}`}
                >
                  {r.priority}
                </span>
              </div>
              <p className="text-sm text-slate-700 mt-0.5">{r.description}</p>
            </div>
          ))}
          {c.acceptanceCriteria?.length > 0 && (
            <div className="pt-3 border-t border-slate-100">
              <h4 className="text-[10px] font-medium text-slate-500 uppercase tracking-wide mb-2">
                Acceptance Criteria
              </h4>
              {c.acceptanceCriteria.map((a: string, i: number) => (
                <p key={i} className="text-xs text-slate-600 py-1 font-mono">
                  {a}
                </p>
              ))}
            </div>
          )}
          {c.constraints?.length > 0 && (
            <div className="pt-3 border-t border-slate-100">
              <h4 className="text-[10px] font-medium text-slate-500 uppercase tracking-wide mb-2">
                Constraints
              </h4>
              {c.constraints.map((x: string, i: number) => (
                <p key={i} className="text-xs text-slate-600 py-0.5">
                  • {x}
                </p>
              ))}
            </div>
          )}
        </div>
      );

    if (activeTab === 'architecture')
      return (
        <div className="space-y-3">
          {c.components?.map((comp: any, i: number) => (
            <div key={i} className="p-3 bg-slate-50 rounded border border-slate-100">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-sm font-medium text-slate-800">{comp.name}</span>
                <code className="text-[10px] px-1.5 py-0.5 bg-blue-50 text-blue-700 rounded">
                  {comp.layer}
                </code>
              </div>
              <ul className="text-xs text-slate-500 space-y-0.5">
                {comp.responsibilities?.map((r: string, j: number) => <li key={j}>→ {r}</li>)}
              </ul>
            </div>
          ))}
          {c.boundedContexts?.length > 0 && (
            <div className="pt-3 border-t border-slate-100">
              <h4 className="text-[10px] font-medium text-slate-500 uppercase tracking-wide mb-2">
                Bounded Contexts
              </h4>
              {c.boundedContexts.map((bc: any, i: number) => (
                <div key={i} className="text-xs text-slate-600 py-1">
                  <span className="font-medium">{bc.name}</span> — {bc.aggregates?.join(', ')}
                </div>
              ))}
            </div>
          )}
        </div>
      );

    if (activeTab === 'tasks')
      return (
        <div className="space-y-2">
          <div className="text-[10px] text-slate-400 mb-3 font-mono">
            {c.tasks?.length} tasks • {c.traceabilityCoverage}% coverage
          </div>
          {c.tasks?.map((t: any) => (
            <div
              key={t.id}
              className="flex items-start gap-3 py-2 border-b border-slate-50 last:border-0"
            >
              <code className="text-[10px] text-blue-600 mt-0.5 whitespace-nowrap">{t.id}</code>
              <div className="flex-1 min-w-0">
                <p className="text-sm text-slate-700">{t.title}</p>
                <p className="text-xs text-slate-400 mt-0.5 truncate">{t.description}</p>
              </div>
              <span className="text-[10px] px-1.5 py-0.5 bg-slate-100 text-slate-500 rounded whitespace-nowrap">
                {t.complexity}/5
              </span>
            </div>
          ))}
        </div>
      );

    return null;
  }

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link to="/" className="text-xs text-slate-400 hover:text-slate-600">
            ← Projects
          </Link>
          <span className="text-xs text-slate-300">/</span>
          <span className="text-sm font-medium text-slate-700">{project?.name || '...'}</span>
        </div>
        {pipelineStatus === 'complete' && (
          <button
            onClick={handleExport}
            className="px-3 py-1.5 text-xs font-medium bg-slate-900 text-white rounded hover:bg-slate-800"
          >
            Export .zip
          </button>
        )}
      </header>

      {/* Pipeline status bar */}
      {pipelineStatus !== 'idle' && (
        <div className="bg-white border-b border-slate-200 px-6 py-2">
          <div className="flex items-center gap-6">
            {stages.map((stage, i) => (
              <div key={stage.key} className="flex items-center gap-2">
                {i > 0 && <span className="text-slate-200 text-xs">→</span>}
                <span
                  className={`w-2 h-2 rounded-full ${
                    stage.status === 'complete'
                      ? 'bg-green-500'
                      : stage.status === 'running'
                        ? 'bg-blue-500 animate-pulse'
                        : stage.status === 'failed'
                          ? 'bg-red-500'
                          : 'bg-slate-200'
                  }`}
                />
                <span
                  className={`text-xs ${
                    stage.status === 'complete'
                      ? 'text-slate-700'
                      : stage.status === 'running'
                        ? 'text-blue-600 font-medium'
                        : stage.status === 'failed'
                          ? 'text-red-600'
                          : 'text-slate-400'
                  }`}
                >
                  {stage.label}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Main content */}
      <main className="flex-1 max-w-4xl w-full mx-auto px-6 py-6">
        {/* Idle: input form */}
        {pipelineStatus === 'idle' && (
          <div className="space-y-4">
            <div>
              <label className="block text-xs font-medium text-slate-600 mb-1.5">
                Project description
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Describe the system you want to architect..."
                rows={10}
                className="w-full px-3 py-2 text-sm border border-slate-200 rounded-md bg-white focus:outline-none focus:ring-1 focus:ring-blue-500 resize-none font-mono"
              />
              <p className="text-[10px] text-slate-400 mt-1 font-mono">
                {description.length} chars
              </p>
            </div>
            <button
              onClick={runPipeline}
              disabled={description.length < 10}
              className="px-4 py-2 text-xs font-medium bg-slate-900 text-white rounded hover:bg-slate-800 disabled:opacity-40 disabled:cursor-not-allowed"
            >
              Run pipeline
            </button>
          </div>
        )}

        {/* Running: just the pipeline bar above handles visualization */}
        {pipelineStatus === 'running' && (
          <div className="py-12 text-center">
            <p className="text-sm text-slate-500">Generating engineering artifacts...</p>
            <p className="text-xs text-slate-400 mt-1">
              This typically takes 15–60 seconds per stage.
            </p>
          </div>
        )}

        {/* Failed */}
        {pipelineStatus === 'failed' && (
          <div className="border border-red-100 bg-red-50 rounded-lg p-4">
            <p className="text-sm text-red-700 font-medium">Pipeline failed</p>
            <p className="text-xs text-red-600 mt-1">{error}</p>
            <button
              onClick={() => setPipelineStatus('idle')}
              className="mt-3 text-xs text-slate-600 hover:text-slate-800 underline"
            >
              Retry
            </button>
          </div>
        )}

        {/* Complete: document viewer */}
        {pipelineStatus === 'complete' && (
          <div className="space-y-4">
            {/* Tab bar */}
            <div className="flex items-center gap-1 border-b border-slate-200">
              {(['spec', 'architecture', 'tasks'] as const).map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-3 py-2 text-xs font-medium border-b-2 transition-colors ${
                    activeTab === tab
                      ? 'border-slate-900 text-slate-900'
                      : 'border-transparent text-slate-400 hover:text-slate-600'
                  }`}
                >
                  {tab === 'spec'
                    ? 'Requirements'
                    : tab === 'architecture'
                      ? 'Architecture'
                      : 'Tasks'}
                </button>
              ))}
              <div className="flex-1" />
              {artifacts[activeTab] && <FeedbackWidget artifactId={artifacts[activeTab].id} />}
            </div>

            {/* Document content */}
            <div className="bg-white border border-slate-200 rounded-lg p-5">
              {renderArtifact(artifacts[activeTab])}
            </div>

            {/* Metadata footer */}
            {metadata && (
              <div className="flex items-center gap-4 text-[10px] text-slate-400 font-mono">
                <span>model: {metadata.model}</span>
                <span>prompt: {metadata.promptVersion}</span>
                <span>chunks: {metadata.ragChunksUsed}</span>
                <span>retries: {metadata.retryCount}</span>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
