import JSZip from 'jszip';
import type { Artifact } from '../db/repositories/artifact-repo.js';
import type { DocumentStore } from './document-store.js';

const TYPE_FILE: Record<string, string> = {
  product_vision: '01-product-vision/vision.md',
  specification: '02-requirements/requirements.md',
  architecture: '03-architecture/architecture.md',
  risk_assessment: '06-risk-assessment/risks.md',
  task_breakdown: '07-tasks/tasks.md',
};

export interface ExportInput {
  projectName: string;
  description?: string;
  artifacts: Artifact[];
}

/**
 * Builds the engineering package (.zip) server-side from stored artifacts.
 * Diagram PNG/SVG rendering is intentionally excluded here — the browser-side
 * export still provides those — to avoid a headless-browser dependency.
 */
export async function buildPackageZip(input: ExportInput): Promise<Buffer> {
  const zip = new JSZip();

  zip.file(
    'README.md',
    `# ${input.projectName} — Engineering Package\n\nGenerated by ArchitectAI.\n\n> ${input.description ?? ''}\n`,
  );

  for (const artifact of input.artifacts) {
    const target = TYPE_FILE[artifact.type];
    if (target) {
      zip.file(target, formatArtifact(artifact.type, artifact.content));
    }
  }

  const diagrams = input.artifacts.find((a) => a.type === 'diagrams');
  if (diagrams) {
    addDiagramSources(zip, diagrams.content);
  }

  const latest = input.artifacts[0];
  zip.file(
    '04_Metadata.md',
    `# Metadata\n\n- **Model:** ${latest?.model ?? 'unknown'}\n- **Prompt:** ${latest?.promptVersion ?? 'unknown'}\n- **Generated:** ${new Date().toISOString()}\n`,
  );

  return Buffer.from(await zip.generateAsync({ type: 'nodebuffer' }));
}

export async function storeExportPackage(
  store: DocumentStore,
  projectId: string,
  data: Buffer,
): Promise<{ key: string; sizeBytes: number }> {
  const key = `exports/${projectId}/${new Date().toISOString().slice(0, 10)}/package.zip`;
  await store.putObject(key, data, 'application/zip');
  return { key, sizeBytes: data.length };
}

function addDiagramSources(zip: JSZip, content: Record<string, unknown>): void {
  const sources: Record<string, string> = {};
  if (typeof content.componentDiagram === 'string') sources['component'] = content.componentDiagram;
  if (typeof content.containerDiagram === 'string') sources['container'] = content.containerDiagram;
  if (typeof content.dataFlowDiagram === 'string') sources['data-flow'] = content.dataFlowDiagram;
  if (typeof content.contextDiagram === 'string') sources['context'] = content.contextDiagram;
  for (const [slug, src] of Object.entries(sources)) {
    zip.file(`04-diagrams/${slug}.mmd`, src);
  }
}

function formatArtifact(type: string, c: Record<string, unknown>): string {
  switch (type) {
    case 'specification':
      return formatSpec(c);
    case 'architecture':
      return formatArch(c);
    case 'product_vision':
      return formatVision(c);
    case 'risk_assessment':
      return formatRisks(c);
    case 'task_breakdown':
      return formatTasks(c);
    default:
      return JSON.stringify(c, null, 2);
  }
}

function str(v: unknown): string {
  return typeof v === 'string' ? v : '';
}

function arr(v: unknown): unknown[] {
  return Array.isArray(v) ? v : [];
}

function formatSpec(c: Record<string, unknown>): string {
  let md = '# Requirements\n\n';
  for (const r of arr(c.functionalRequirements)) {
    const id = str((r as Record<string, unknown>).id);
    const description = str((r as Record<string, unknown>).description);
    const priority = str((r as Record<string, unknown>).priority);
    md += `## ${id}: ${description}\n\n**Priority:** ${priority}\n\n`;
  }
  md += '## Acceptance Criteria\n\n';
  for (const a of arr(c.acceptanceCriteria)) md += `- ${str(a)}\n`;
  md += '\n## Constraints\n\n';
  for (const x of arr(c.constraints)) md += `- ${str(x)}\n`;
  md += '\n## Dependencies\n\n';
  for (const x of arr(c.dependencies)) md += `- ${str(x)}\n`;
  return md;
}

function formatArch(c: Record<string, unknown>): string {
  let md = '# Architecture\n\n';
  for (const x of arr(c.components)) {
    const comp = x as Record<string, unknown>;
    md += `## ${str(comp.name)} [${str(comp.layer)}]\n\n`;
    md += `${arr(comp.responsibilities).map((r) => `- ${str(r)}`).join('\n')}\n\n`;
  }
  md += '## Bounded Contexts\n\n';
  for (const x of arr(c.boundedContexts)) {
    const bc = x as Record<string, unknown>;
    md += `### ${str(bc.name)}\n\nAggregates: ${arr(bc.aggregates).join(', ')}\n\n`;
  }
  return md;
}

function formatVision(c: Record<string, unknown>): string {
  let md = '# Product Vision\n\n';
  md += `## Vision\n${str(c.vision)}\n\n`;
  md += `## Problem\n${str(c.problem)}\n\n`;
  md += '## Target Users\n';
  for (const u of arr(c.targetUsers)) md += `- ${str(u)}\n`;
  md += '\n## Business Goals\n';
  for (const g of arr(c.businessGoals)) md += `- ${str(g)}\n`;
  md += '\n## Core Capabilities\n';
  for (const cap of arr(c.coreCapabilities)) md += `- ${str(cap)}\n`;
  md += '\n## Success Metrics\n';
  for (const m of arr(c.successMetrics)) md += `- ${str(m)}\n`;
  return md;
}

function formatRisks(c: Record<string, unknown>): string {
  let md = '# Risk Assessment\n\n';
  for (const r of arr(c.risks)) {
    const risk = r as Record<string, unknown>;
    md += `## ${str(risk.id)}: ${str(risk.description)}\n\n`;
    md += `- **Category:** ${str(risk.category)}\n`;
    md += `- **Severity:** ${str(risk.severity)}\n`;
    md += `- **Mitigation:** ${str(risk.mitigation)}\n\n`;
  }
  return md;
}

function formatTasks(c: Record<string, unknown>): string {
  let md = `# Tasks\n\nCoverage: ${str(c.traceabilityCoverage)}%\n\n`;
  for (const t of arr(c.tasks)) {
    const task = t as Record<string, unknown>;
    md += `## ${str(task.id)}: ${str(task.title)}\n\n`;
    md += `Complexity: ${str(task.complexity)}/5\n\n${str(task.description)}\n\n`;
  }
  return md;
}
